import path from "node:path";
import { pathToFileURL } from "node:url";

import type { LatestRegistryPointer, NodeSpec, NormalizedRegistrySnapshot, ParamSpec, ValueKind } from "./types.ts";

import { getLatestPointerPath } from "./store.ts";
import { LatestRegistryPointerSchema } from "./zod.ts";
import { readJsonFile } from "../shared/json.ts";
import { resolveProjectPath, writeTextFile } from "../shared/fs.ts";

const GENERATED_OUTPUT_PATH = resolveProjectPath("src", "v2", "generated", "node-schemas.ts");

const SUPPORTED_PARAM_KINDS = new Set<ValueKind>([
  "text",
  "number",
  "boolean",
  "enum",
  "image",
  "video",
  "audio",
  "mask",
  "3d",
  "array",
  "object",
  "any",
  "file",
  "json",
]);

export interface GenerateNodeZodWarning {
  code: string;
  definitionId: string;
  nodeType: string;
  paramKey: string;
  message: string;
}

export interface GenerateNodeZodResult {
  outputPath: string;
  snapshotPath: string;
  warningCount: number;
  warnings: GenerateNodeZodWarning[];
  definitionCount: number;
  uniqueNodeTypeCount: number;
  uniquePortKindCount: number;
  uniqueParamKindCount: number;
}

export async function generateNodeZodSchemas(options?: {
  normalizedSnapshotPath?: string;
  outputPath?: string;
}): Promise<GenerateNodeZodResult> {
  const snapshotPath = options?.normalizedSnapshotPath || (await getLatestNormalizedSnapshotPath());
  const outputPath = options?.outputPath || GENERATED_OUTPUT_PATH;

  const snapshot = await readNormalizedSnapshot(snapshotPath);

  const warnings: GenerateNodeZodWarning[] = [];
  const generatedSource = renderGeneratedSource(snapshot, snapshotPath, warnings);
  await writeTextFile(outputPath, generatedSource);

  return {
    outputPath,
    snapshotPath,
    warningCount: warnings.length,
    warnings,
    definitionCount: snapshot.nodeSpecs.length,
    uniqueNodeTypeCount: new Set(snapshot.nodeSpecs.map((nodeSpec) => nodeSpec.nodeType)).size,
    uniquePortKindCount: new Set(snapshot.nodeSpecs.flatMap((nodeSpec) => nodeSpec.ports.map((port) => port.kind))).size,
    uniqueParamKindCount: new Set(snapshot.nodeSpecs.flatMap((nodeSpec) => nodeSpec.params.map((param) => param.kind))).size,
  };
}

async function getLatestNormalizedSnapshotPath(): Promise<string> {
  const latestPointer = LatestRegistryPointerSchema.parse(
    await readJsonFile<LatestRegistryPointer>(getLatestPointerPath()),
  );
  return latestPointer.normalizedSnapshotPath;
}

async function readNormalizedSnapshot(snapshotPath: string): Promise<NormalizedRegistrySnapshot> {
  const snapshot = await readJsonFile<NormalizedRegistrySnapshot>(snapshotPath);
  if (!snapshot || typeof snapshot !== "object") {
    throw new Error(`Normalized snapshot at ${snapshotPath} is not an object.`);
  }
  if (!Array.isArray(snapshot.nodeSpecs)) {
    throw new Error(`Normalized snapshot at ${snapshotPath} is missing nodeSpecs[].`);
  }
  if (typeof snapshot.syncId !== "string" || typeof snapshot.registryVersion !== "string") {
    throw new Error(`Normalized snapshot at ${snapshotPath} is missing syncId/registryVersion.`);
  }
  return snapshot;
}

function renderGeneratedSource(
  snapshot: NormalizedRegistrySnapshot,
  snapshotPath: string,
  warnings: GenerateNodeZodWarning[],
): string {
  const nodeSpecs = [...snapshot.nodeSpecs].sort((left, right) =>
    left.source.definitionId.localeCompare(right.source.definitionId),
  );
  const nodeTypes = uniqueSorted(nodeSpecs.map((nodeSpec) => nodeSpec.nodeType));
  const portKinds = uniqueSorted(nodeSpecs.flatMap((nodeSpec) => nodeSpec.ports.map((port) => port.kind)));
  const paramKinds = uniqueSorted(nodeSpecs.flatMap((nodeSpec) => nodeSpec.params.map((param) => param.kind)));
  const definitionIds = nodeSpecs.map((nodeSpec) => nodeSpec.source.definitionId);

  for (const nodeSpec of nodeSpecs) {
    for (const param of nodeSpec.params) {
      if (!SUPPORTED_PARAM_KINDS.has(param.kind)) {
        throw new Error(
          `Unsupported param kind \`${param.kind}\` for ${nodeSpec.source.definitionId}:${param.key}. ` +
            "Generated runtime contracts must not silently fall back to unknown.",
        );
      }

      if (param.kind === "enum" && (!param.enumValues || param.enumValues.length === 0)) {
        throw new Error(
          `Enum param \`${nodeSpec.source.definitionId}:${param.key}\` is missing enumValues in normalized snapshot.`,
        );
      }
    }
  }

  const definitionIdsByNodeType = groupDefinitionIdsByNodeType(nodeSpecs);
  const paramSchemaEntries = nodeSpecs.map((nodeSpec) => renderNodeParamSchemaEntry(nodeSpec, warnings));

  return [
    "// Generated by src/v2/registry/generate-node-zod.ts",
    `// Source snapshot: ${snapshotPath}`,
    `// syncId: ${snapshot.syncId}`,
    `// registryVersion: ${snapshot.registryVersion}`,
    "",
    'import { z } from "zod";',
    "",
    `export const GeneratedRegistrySyncId = ${quote(snapshot.syncId)};`,
    `export const GeneratedRegistryVersion = ${quote(snapshot.registryVersion)};`,
    "",
    "export const RegistrySourceKindSchema = z.enum([\"public\", \"user\"] as const);",
    "export const SpendBehaviorSchema = z.enum([\"credits\", \"free\", \"unknown\"] as const);",
    "export const PortDirectionSchema = z.enum([\"input\", \"output\"] as const);",
    "",
    "export const JsonValueSchema: z.ZodTypeAny = z.lazy(() =>",
    "  z.union([",
    "    z.string(),",
    "    z.number(),",
    "    z.boolean(),",
    "    z.null(),",
    "    z.array(JsonValueSchema),",
    "    z.record(z.string(), JsonValueSchema),",
    "  ]),",
    ");",
    "",
    "export const AssetInputSchema = z",
    "  .object({",
    "    assetId: z.string().min(1).optional(),",
    "    uri: z.string().min(1).optional(),",
    "    mimeType: z.string().min(1).optional(),",
    "    filename: z.string().min(1).optional(),",
    "    metadata: z.record(z.string(), JsonValueSchema).optional(),",
    "  })",
    "  .refine((value) => Boolean(value.assetId || value.uri), {",
    "    message: \"Asset input requires `assetId` or `uri`.\",",
    "  });",
    "",
    renderEnumSchema("NodeDefinitionIdSchema", definitionIds),
    "",
    renderEnumSchema("NodeTypeSchema", nodeTypes),
    "",
    renderEnumSchema("PortKindSchema", portKinds),
    "",
    renderEnumSchema("ParamKindSchema", paramKinds),
    "",
    "export const ParamUiSpecSchema = z.object({",
    "  control: z.enum([\"textbox\", \"textarea\", \"slider\", \"toggle\", \"select\", \"file\"] as const).optional(),",
    "  label: z.string().optional(),",
    "  group: z.string().optional(),",
    "  order: z.number().int().optional(),",
    "  hidden: z.boolean().optional(),",
    "});",
    "",
    "export const ParamAppModeSpecSchema = z.object({",
    "  exposable: z.boolean(),",
    "  defaultExposed: z.boolean(),",
    "  lockable: z.boolean(),",
    "});",
    "",
    "export const PortSpecSchema = z.object({",
    "  key: z.string(),",
    "  direction: PortDirectionSchema,",
    "  kind: PortKindSchema,",
    "  required: z.boolean(),",
    "  multi: z.boolean(),",
    "  accepts: z.array(PortKindSchema).optional(),",
    "  produces: z.array(PortKindSchema).optional(),",
    "  raw: z.unknown().optional(),",
    "});",
    "",
    "export const ParamSpecSchema = z.object({",
    "  key: z.string(),",
    "  kind: ParamKindSchema,",
    "  required: z.boolean(),",
    "  defaultValue: z.unknown().optional(),",
    "  enumValues: z.array(z.string()).optional(),",
    "  min: z.number().optional(),",
    "  max: z.number().optional(),",
    "  step: z.number().optional(),",
    "  ui: ParamUiSpecSchema.optional(),",
    "  appMode: ParamAppModeSpecSchema.optional(),",
    "  raw: z.unknown().optional(),",
    "});",
    "",
    "export const NodeModelSpecSchema = z.object({",
    "  provider: z.string().optional(),",
    "  name: z.string().optional(),",
    "  pricingKey: z.string().optional(),",
    "  matchedPriceCredits: z.number().nullable().optional(),",
    "});",
    "",
    "export const NodeCompatibilitySpecSchema = z.object({",
    "  acceptsKinds: z.array(PortKindSchema),",
    "  producesKinds: z.array(PortKindSchema),",
    "  requiresAllMandatoryInputs: z.boolean(),",
    "});",
    "",
    "export const NodeAppModeSpecSchema = z.object({",
    "  supportsOutputNode: z.boolean(),",
    "  exposableParams: z.array(z.string()),",
    "  exposablePorts: z.array(z.string()),",
    "});",
    "",
    "export const NodeSpecSourceSchema = z.object({",
    "  definitionId: NodeDefinitionIdSchema,",
    "  fetchedAt: z.string(),",
    "  sourceKind: RegistrySourceKindSchema,",
    "  rawHash: z.string(),",
    "});",
    "",
    "export const NodeSpecSchema = z.object({",
    "  registryVersion: z.string(),",
    "  syncId: z.string(),",
    "  source: NodeSpecSourceSchema,",
    "  nodeType: NodeTypeSchema,",
    "  displayName: z.string(),",
    "  category: z.string().optional(),",
    "  subtype: z.string().optional(),",
    "  isGenerative: z.boolean(),",
    "  spendBehavior: SpendBehaviorSchema,",
    "  model: NodeModelSpecSchema.optional(),",
    "  ports: z.array(PortSpecSchema),",
    "  params: z.array(ParamSpecSchema),",
    "  compatibility: NodeCompatibilitySpecSchema,",
    "  appMode: NodeAppModeSpecSchema,",
    "  raw: z.unknown().optional(),",
    "});",
    "",
    "export const DefinitionIdsByNodeType = {",
    ...Object.entries(definitionIdsByNodeType).flatMap(([nodeType, ids]) => [
      `  ${renderObjectKey(nodeType)}: ${renderConstStringArray(ids)},`,
    ]),
    "} as const;",
    "",
    "export const NodeParamSchemasByDefinitionId = {",
    ...paramSchemaEntries.map((entry) => `  ${renderObjectKey(entry.definitionId)}: ${entry.schemaSource},`),
    "} as const;",
    "",
    "export const NodeParamMetadataByDefinitionId = {",
    ...nodeSpecs.flatMap((nodeSpec) => [
      `  ${renderObjectKey(nodeSpec.source.definitionId)}: {`,
      `    nodeType: ${quote(nodeSpec.nodeType)},`,
      `    displayName: ${quote(nodeSpec.displayName)},`,
      `    paramKeys: ${renderConstStringArray(nodeSpec.params.map((param) => param.key))},`,
      "  },",
    ]),
    "} as const;",
    "",
  ].join("\n");
}

function renderNodeParamSchemaEntry(
  nodeSpec: NodeSpec,
  warnings: GenerateNodeZodWarning[],
): {
  definitionId: string;
  schemaSource: string;
} {
  const fields = nodeSpec.params.map((param) => {
    const schemaSource = renderParamFieldSchema(nodeSpec, param, warnings);
    return `${renderObjectKey(param.key)}: ${schemaSource}`;
  });

  const schemaSource = fields.length > 0 ? `z.object({ ${fields.join(", ")} }).strict()` : "z.object({}).strict()";

  return {
    definitionId: nodeSpec.source.definitionId,
    schemaSource,
  };
}

function renderParamFieldSchema(
  nodeSpec: NodeSpec,
  param: ParamSpec,
  warnings: GenerateNodeZodWarning[],
): string {
  const baseSchema = renderRequiredParamSchema(nodeSpec, param, warnings);
  return param.required ? baseSchema : `${baseSchema}.optional()`;
}

function renderRequiredParamSchema(
  nodeSpec: NodeSpec,
  param: ParamSpec,
  warnings: GenerateNodeZodWarning[],
): string {
  switch (param.kind) {
    case "text":
      return "z.string()";
    case "number":
      return applyNumberBounds(renderNumericSchema(param), param);
    case "boolean":
      return "z.boolean()";
    case "enum":
      return renderEnumSchemaExpression(param.enumValues || []);
    case "array":
      return renderArraySchema(nodeSpec, param, warnings);
    case "object":
      return "z.record(z.string(), z.unknown())";
    case "any":
      return "z.any()";
    case "json":
      return "JsonValueSchema";
    case "image":
    case "video":
    case "audio":
    case "mask":
    case "3d":
    case "file":
      return "AssetInputSchema";
    case "unknown":
      throw new Error(
        `Unsupported param kind \`${param.kind}\` for ${nodeSpec.source.definitionId}:${param.key}.`,
      );
    default:
      return assertUnreachable(param.kind);
  }
}

function renderNumericSchema(param: ParamSpec): string {
  const rawType = firstString(asRecord(param.raw).type, asRecord(param.raw).format)?.toLowerCase() || "";
  if (rawType === "integer" || rawType === "input-integer") {
    return "z.number().int()";
  }
  return "z.number()";
}

function applyNumberBounds(schemaSource: string, param: ParamSpec): string {
  let expression = schemaSource;
  if (typeof param.min === "number") {
    expression += `.min(${param.min})`;
  }
  if (typeof param.max === "number") {
    expression += `.max(${param.max})`;
  }
  return expression;
}

function renderArraySchema(
  nodeSpec: NodeSpec,
  param: ParamSpec,
  warnings: GenerateNodeZodWarning[],
): string {
  const raw = asRecord(param.raw);
  const itemTypeToken = firstString(raw.array_type, raw.items && asRecord(raw.items).type);
  let itemSchemaSource = "z.unknown()";

  if (itemTypeToken) {
    itemSchemaSource = renderArrayItemSchema(itemTypeToken, nodeSpec, param);
  } else {
    const inferred = inferArrayItemSchemaFromDefault(param.defaultValue);
    if (inferred) {
      itemSchemaSource = inferred;
    } else {
      warnings.push({
        code: "array-item-kind-missing",
        definitionId: nodeSpec.source.definitionId,
        nodeType: nodeSpec.nodeType,
        paramKey: param.key,
        message:
          "Array param is missing `array_type`/`items.type`; generated schema falls back to `z.array(z.unknown())`.",
      });
    }
  }

  let expression = `z.array(${itemSchemaSource})`;
  if (typeof raw.minItems === "number") {
    expression += `.min(${raw.minItems})`;
  }
  if (typeof raw.maxItems === "number") {
    expression += `.max(${raw.maxItems})`;
  }
  return expression;
}

function renderArrayItemSchema(token: string, nodeSpec: NodeSpec, param: ParamSpec): string {
  const normalized = token.trim().toLowerCase();

  if (normalized === "string" || normalized === "text") {
    return "z.string()";
  }
  if (normalized === "number" || normalized === "input-number") {
    return "z.number()";
  }
  if (normalized === "integer" || normalized === "input-integer" || normalized === "seed") {
    return "z.number().int()";
  }
  if (normalized === "boolean") {
    return "z.boolean()";
  }
  if (normalized === "object" || normalized === "json") {
    return "z.record(z.string(), z.unknown())";
  }
  if (normalized === "any") {
    return "z.any()";
  }
  if (
    normalized === "image" ||
    normalized === "video" ||
    normalized === "audio" ||
    normalized === "mask" ||
    normalized === "file" ||
    normalized === "3d"
  ) {
    return "AssetInputSchema";
  }

  throw new Error(
    `Unsupported array item type \`${token}\` for ${nodeSpec.source.definitionId}:${param.key}.`,
  );
}

function inferArrayItemSchemaFromDefault(defaultValue: unknown): string | null {
  if (!Array.isArray(defaultValue) || defaultValue.length === 0) {
    return null;
  }

  const elementTypes = uniqueSorted(defaultValue.map((value) => inferDefaultElementType(value)).filter(Boolean) as string[]);
  if (elementTypes.length !== 1) {
    return null;
  }

  switch (elementTypes[0]) {
    case "string":
      return "z.string()";
    case "number":
      return "z.number()";
    case "boolean":
      return "z.boolean()";
    case "object":
      return "z.record(z.string(), z.unknown())";
    default:
      return null;
  }
}

function inferDefaultElementType(value: unknown): string | null {
  if (typeof value === "string") {
    return "string";
  }
  if (typeof value === "number") {
    return "number";
  }
  if (typeof value === "boolean") {
    return "boolean";
  }
  if (value && typeof value === "object" && !Array.isArray(value)) {
    return "object";
  }
  return null;
}

function groupDefinitionIdsByNodeType(nodeSpecs: NodeSpec[]): Record<string, string[]> {
  const grouped: Record<string, string[]> = {};

  for (const nodeSpec of nodeSpecs) {
    if (!grouped[nodeSpec.nodeType]) {
      grouped[nodeSpec.nodeType] = [];
    }
    grouped[nodeSpec.nodeType].push(nodeSpec.source.definitionId);
  }

  for (const nodeType of Object.keys(grouped)) {
    grouped[nodeType].sort();
  }

  return Object.fromEntries(
    Object.entries(grouped).sort(([left], [right]) => left.localeCompare(right)),
  );
}

function renderEnumSchema(name: string, values: string[]): string {
  return `export const ${name} = z.enum(${renderConstStringArray(values)});`;
}

function renderEnumSchemaExpression(values: string[]): string {
  if (values.length === 0) {
    throw new Error("Cannot generate z.enum([]) for enum param without values.");
  }

  return `z.enum(${renderConstStringArray(values)})`;
}

function renderConstStringArray(values: string[]): string {
  return `[${values.map((value) => quote(value)).join(", ")}] as const`;
}

function renderObjectKey(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : quote(key);
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function uniqueSorted(values: string[]): string[] {
  return Array.from(new Set(values)).sort((left, right) => left.localeCompare(right));
}

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value) ? (value as Record<string, unknown>) : {};
}

function firstString(...values: unknown[]): string | undefined {
  for (const value of values) {
    if (typeof value === "string" && value.trim()) {
      return value.trim();
    }
  }

  return undefined;
}

function assertUnreachable(value: never): never {
  throw new Error(`Unreachable value: ${String(value)}`);
}

const isMainModule = process.argv[1]
  ? import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href
  : false;

if (isMainModule) {
  generateNodeZodSchemas()
    .then((result) => {
      console.log(`[generate-node-zod] snapshot=${result.snapshotPath}`);
      console.log(`[generate-node-zod] output=${result.outputPath}`);
      console.log(
        `[generate-node-zod] definitions=${result.definitionCount} nodeTypes=${result.uniqueNodeTypeCount} portKinds=${result.uniquePortKindCount} paramKinds=${result.uniqueParamKindCount} warnings=${result.warningCount}`,
      );

      for (const warning of result.warnings) {
        console.warn(
          `[generate-node-zod] warning code=${warning.code} definitionId=${warning.definitionId} nodeType=${warning.nodeType} param=${warning.paramKey} message=${warning.message}`,
        );
      }
    })
    .catch((error) => {
      console.error(`[generate-node-zod] error=${error.message}`);
      process.exitCode = 1;
    });
}
